### ISSUE TITLE
Solution files missing

### ISSUE THREAD

**Issue by avail** [NotMichaelChen/TDA#1]
Your current .gitignore removes all of the Visual Studio solution (.sln/.csproj) files, making it a tad hard to build

**Comment by NotMichaelChen** [comment]
Ah lmao, I completely forgot about that. I stopped using an IDE a while ago, so I was just compiling from the console. Is there anything else I should change about the .gitignore?

**Comment by avail** [comment]
Everything else is just fine. I also build it from the console, yes, but other people might not know how to.
An entry on how to build in the README would be nice :)

**Comment by NotMichaelChen** [comment]
Hm ok, I'll add a short bit on how to build in the README then.
